import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:hy5mwe */}
        {/* pv-block-start:m35qst */}
        <div data-pv-block="m35qst" className="flex flex-col gap-2 items-center pt-16" data-pv-sketchpad-el="m35qst" style={{ position: 'absolute', left: 100, top: 100 }}>
          {/* pv-editable-zone-start:ger2rz */}
          {/* pv-block-start:f9j9gf */}
          <h1 data-pv-block="f9j9gf" className="animate-[hero-rise_700ms_ease-out_both] leading-[0.98] max-w-[14ch] tracking-tighter font-secondary font-extrabold mx-auto text-[clamp(44px,9vw,72px)]">
            Design by hand.<br />Prototype with AI.<br /><span className="text-foreground-primary"> Stay pixel-perfect. </span>
          </h1>
          {/* pv-block-end:f9j9gf */}
          {/* pv-block-start:5gtfnu */}
          <p data-pv-block="5gtfnu" className="animate-[hero-rise_700ms_ease-out_both] [animation-delay:80ms] text-[clamp(16px,1.3vw,19px)] text-foreground-default mt-6 mx-auto text-balance max-w-[75ch]">
            Protovibe Studio is the open-source tool for UX/UI designers who love the power of vibe-coding but refuse to hand off hallucinated slop. It runs locally in pure React, so you and your coding agent are finally on the same page.
          </p>
          {/* pv-block-end:5gtfnu */}
          {/* pv-block-start:ejfe56 */}
          <div data-pv-block="ejfe56" className="animate-[hero-rise_700ms_ease-out_both] [animation-delay:160ms] flex gap-[12px] mt-[36px] flex-wrap justify-center flex-col items-stretch min-w-64">
            {/* pv-editable-zone-start:z00108 */}
              {/* pv-block-start:pwvom1 */}
              <Button rightIcon="mdi:arrow-right" data-pv-block="pwvom1" data-install label="Download" variant="solid" color="primary" size="lg" />
              {/* pv-block-end:pwvom1 */}
        
              {/* pv-block-start:aurii6 */}
              <Button leftIcon="carbon:demo" data-pv-block="aurii6" label="Demo in Codesandbox" variant="solid" color="neutral" size="lg" />
              {/* pv-block-end:aurii6 */}
        
              {/* pv-block-start:x3xjwk */}
              <Button leftIcon="mdi:github" data-pv-block="x3xjwk" label="Star on GitHub" variant="ghost" color="neutral" size="lg" />
              {/* pv-block-end:x3xjwk */}
            {/* pv-editable-zone-end:z00108 */}
          </div>
          {/* pv-block-end:ejfe56 */}
          {/* pv-editable-zone-end:ger2rz */}
        </div>
        {/* pv-block-end:m35qst */}
      {/* pv-editable-zone-end:hy5mwe */}
    </div>
  );
}
