import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:bibqg8 */}
        {/* pv-block-start:qvh9pj */}
        <div data-pv-block="qvh9pj" className="flex flex-col gap-2 items-center pt-16 text-center" data-pv-sketchpad-el="qvh9pj" style={{ position: 'absolute', left: 292, top: 108 }}>
          {/* pv-editable-zone-start:ger2rz */}
            {/* pv-block-start:8f7ytz */}
            <div data-pv-block="8f7ytz" className="font-bold text-[12px] tracking-[0.18em] uppercase mb-[16px] text-foreground-primary" >
              Open-source tool
            </div>
            {/* pv-block-end:8f7ytz */}
          {/* pv-block-start:64gjbm */}
          <h1 data-pv-block="64gjbm" className="animate-[hero-rise_700ms_ease-out_both] leading-[0.98] max-w-[14ch] tracking-tighter font-secondary font-extrabold mx-auto text-[clamp(44px,9vw,72px)]">
            Design pixel-perfect prototypes with AI
          </h1>
          {/* pv-block-end:64gjbm */}
          {/* pv-block-start:fv9i0e */}
          <p data-pv-block="fv9i0e" className="animate-[hero-rise_700ms_ease-out_both] [animation-delay:80ms] text-[clamp(16px,1.3vw,19px)] text-foreground-default mt-6 mx-auto text-balance max-w-[75ch]">
            Protovibe Studio is a free tool for UX/UI designers who love the power of vibe-coding but refuse to hand off hallucinated slop. It runs in pure React, so you and your coding agent are finally on the same page.
          </p>
          {/* pv-block-end:fv9i0e */}
          {/* pv-block-start:zo29a4 */}
          <div data-pv-block="zo29a4" className="animate-[hero-rise_700ms_ease-out_both] [animation-delay:160ms] flex gap-[12px] mt-[36px] flex-wrap justify-center flex-col items-stretch min-w-64">
            {/* pv-editable-zone-start:z00108 */}
              {/* pv-block-start:jc7whk */}
              <Button rightIcon="mdi:arrow-right" data-pv-block="jc7whk" data-install label="Download" variant="solid" color="primary" size="lg" />
              {/* pv-block-end:jc7whk */}
        
              {/* pv-block-start:5m2ug7 */}
              <Button leftIcon="carbon:demo" data-pv-block="5m2ug7" label="Demo in Codesandbox" variant="solid" color="neutral" size="lg" />
              {/* pv-block-end:5m2ug7 */}
        
              {/* pv-block-start:uowhk3 */}
              <Button leftIcon="mdi:github" data-pv-block="uowhk3" label="Star on GitHub" variant="ghost" color="neutral" size="lg" />
              {/* pv-block-end:uowhk3 */}
            {/* pv-editable-zone-end:z00108 */}
          </div>
          {/* pv-block-end:zo29a4 */}
          {/* pv-editable-zone-end:ger2rz */}
        </div>
        {/* pv-block-end:qvh9pj */}
      {/* pv-editable-zone-end:bibqg8 */}
    </div>
  );
}
