import { Card } from '@/components/ui/card'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { DialogOverlay } from '@/components/ui/dialog-overlay'
import { DialogWindow } from '@/components/ui/dialog-window'
// Auto-generated by Protovibe Sketchpad

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:wial0k */}
        {/* pv-block-start:na9n7k */}
        <DialogOverlay className="flex flex-col overflow-hidden items-center justify-start" data-pv-block="na9n7k" data-pv-sketchpad-el="na9n7k" style={{ position: 'absolute', left: 0, top: -8 }}>
          {/* pv-editable-zone-start:w3fgtu */}
            {/* pv-block-start:tt9ibj */}
            <DialogWindow className="max-h-full overflow-auto" data-pv-block="tt9ibj" >
              {/* pv-editable-zone-start:c9syxy */}
                {/* pv-block-start:oavs1y */}
                <div data-pv-block="oavs1y" className="p-8 flex flex-col gap-2 justify-center items-start">
                  {/* pv-editable-zone-start:q5tfc6 */}
                    {/* pv-block-start:3gfcyb */}
                    <h2 data-pv-block="3gfcyb" className="text-xl font-semibold text-foreground-default">Dialog Title</h2>
                    {/* pv-block-end:3gfcyb */}
                    {/* pv-block-start:2smwac */}
                    <div data-pv-block="2smwac" className="flex flex-col gap-2">
                      {/* pv-editable-zone-start:6cn0k3 */}
                      {/* pv-block-start:anstet */}
                      <p data-pv-block="anstet" className="text-foreground-secondary">This is the modal dialog content. Click the button below or press Escape to close.</p>
                      {/* pv-block-end:anstet */}
                      {/* pv-block-start:y0tn0f */}
                      <p data-pv-block="y0tn0f" className="text-foreground-secondary">This is the modal dialog content. Click the button below or press Escape to close.</p>
                      {/* pv-block-end:y0tn0f */}
                      {/* pv-block-start:sir6zz */}
                      <p data-pv-block="sir6zz" className="text-foreground-secondary">This is the modal dialog content. Click the button below or press Escape to close.</p>
                      {/* pv-block-end:sir6zz */}
                      {/* pv-block-start:fo1cuc */}
                      <p data-pv-block="fo1cuc" className="text-foreground-secondary">This is the modal dialog content. Click the button below or press Escape to close.</p>
                      {/* pv-block-end:fo1cuc */}
                      {/* pv-block-start:fscii2 */}
                      <p data-pv-block="fscii2" className="text-foreground-secondary">This is the modal dialog content. Click the button below or press Escape to close.</p>
                      {/* pv-block-end:fscii2 */}
                      {/* pv-block-start:3u3uer */}
                      <p data-pv-block="3u3uer" className="text-foreground-secondary">This is the modal dialog content. Click the button below or press Escape to close.</p>
                      {/* pv-block-end:3u3uer */}
                      {/* pv-block-start:wlkufn */}
                      <p data-pv-block="wlkufn" className="text-foreground-secondary">This is the modal dialog content. Click the button below or press Escape to close.</p>
                      {/* pv-block-end:wlkufn */}
                      {/* pv-block-start:bhh995 */}
                      <p data-pv-block="bhh995" className="text-foreground-secondary">
                        This is the modal dialog content. Click the button below or press Escape to close. This is the modal dialog content. Click the button below or press Escape to close. This is the modal dialog content. Click the button below or press Escape to close.This is the modal dialog content. Click the button below or press Escape to close. This is the modal dialog content. Click the button below or press Escape to close. This is the modal dialog content. Click the button below or press Escape to close. This is the modal dialog content. Click the button below or press Escape to close.This is the modal dialog content. Click the button below or press Escape to close.
                      </p>
                      {/* pv-block-end:bhh995 */}
                      {/* pv-editable-zone-end:6cn0k3 */}
                    </div>
                    {/* pv-block-end:2smwac */}
                  {/* pv-editable-zone-end:q5tfc6 */}
                </div>
                {/* pv-block-end:oavs1y */}
              {/* pv-editable-zone-end:c9syxy */}
            </DialogWindow>
            {/* pv-block-end:tt9ibj */}
          {/* pv-editable-zone-end:w3fgtu */}
        </DialogOverlay>
        {/* pv-block-end:na9n7k */}
      {/* pv-editable-zone-end:wial0k */}
    </div>
  );
}
