// plugins/protovibe/src/ui/utils/domSnapshot.ts
//
// Serializes a live DOM subtree (inside the app iframe) into a JSON tree that
// the backend /__convert-to-sketchpad endpoint can turn into flat, logic-free
// JSX. The shell has same-origin access to the iframe DOM, so this runs
// synchronously on the real elements.

export interface SnapshotRect {
  left: number;
  top: number;
  width: number;
  height: number;
}

export interface SnapshotNode {
  kind: 'element' | 'text';
  /** Collapsed text content (text nodes only). */
  text?: string;
  /** Lowercased tag name (element nodes only). SVG keeps its real tag. */
  tag?: string;
  /** Raw class attribute value. */
  className?: string;
  /** Safelisted non-protovibe attributes (kebab/native names, values raw). */
  attrs?: Record<string, string>;
  /** data-pv-component-id when present. */
  componentId?: string;
  /** data-pv-block id when present. */
  pvBlockId?: string;
  /**
   * Resolved component props read from the React fiber tree (dev mode).
   * Primitives only — the most faithful source, it sees icons, labels and
   * every dynamic expression already evaluated.
   */
  props?: Record<string, string | number | boolean>;
  /**
   * True when the component instance was passed a `children` prop (per its
   * fiber). Lets the converter recover map-rendered children that carry no
   * data-pv-block markers by falling back to the rendered DOM.
   */
  hasChildrenProp?: boolean;
  /** App-level source locator (data-pv-loc-app-<hash> suffix), for AST prop recovery. */
  locId?: string;
  /** True when the node lives inside an <svg> subtree. */
  isSvg?: boolean;
  /** Viewport-absolute bounding rect (iframe coordinate space). */
  rect?: SnapshotRect;
  children?: SnapshotNode[];
}

export interface DomSnapshot {
  root: SnapshotNode;
  foundComponents: Array<{ componentId: string; count: number }>;
}

const SKIPPED_TAGS = new Set(['script', 'style', 'link', 'template', 'noscript', 'meta']);

// Attributes we never carry over: protovibe bookkeeping, inline styles
// (regenerated by the converter) and ids (would duplicate).
function isDroppedAttr(name: string): boolean {
  return (
    name === 'style' ||
    name === 'id' ||
    name === 'class' ||
    name.startsWith('on') ||
    name.startsWith('data-pv-')
  );
}

// Resolve a fiber's component display name across plain functions, forwardRef
// and memo wrappers.
function fiberTypeName(t: any): string | null {
  if (!t) return null;
  if (typeof t === 'function') return t.displayName || t.name || null;
  if (typeof t === 'object') {
    return (
      t.displayName ||
      t.render?.displayName || t.render?.name || // forwardRef
      t.type?.displayName || t.type?.name || // memo
      null
    );
  }
  return null;
}

/**
 * Read the resolved props of the component instance that rendered `el`, via
 * React's dev-mode fiber attached to the DOM node. Walks up the fiber tree to
 * the nearest component whose name matches `componentId` and returns its
 * `memoizedProps`, filtered to serializable primitives. Returns null when the
 * fiber is unavailable (e.g. production build) — callers fall back to
 * source-AST / data-attribute recovery.
 */
function getFiberComponentProps(
  el: Element,
  componentId: string,
): { props: Record<string, string | number | boolean>; hasChildren: boolean } | null {
  const fiberKey = Object.keys(el).find(k => k.startsWith('__reactFiber$'));
  if (!fiberKey) return null;
  let fiber: any = (el as any)[fiberKey];
  for (let depth = 0; fiber && depth < 40; depth++) {
    if (fiberTypeName(fiber.type) === componentId) {
      const out: Record<string, string | number | boolean> = {};
      const props = fiber.memoizedProps || {};
      for (const [key, value] of Object.entries(props)) {
        if (key === 'children' || key.startsWith('data-pv-')) continue;
        if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
          out[key] = value;
        }
      }
      return { props: out, hasChildren: props.children !== undefined && props.children !== null };
    }
    fiber = fiber.return;
  }
  return null;
}

function toRect(r: DOMRect): SnapshotRect {
  // Layout sizes are fractional (e.g. 83.4px); rounding them down produces
  // boxes slightly smaller than the rendered content and makes text wrap.
  // Ceil the dimensions so the frozen box always fits its content.
  return {
    left: Math.round(r.left),
    top: Math.round(r.top),
    width: Math.ceil(r.width),
    height: Math.ceil(r.height),
  };
}

function walkElement(el: Element, insideSvg: boolean, counts: Map<string, number>): SnapshotNode | null {
  const tag = el.tagName.toLowerCase();
  if (SKIPPED_TAGS.has(tag)) return null;
  if (el.hasAttribute('data-pv-ui')) return null;

  const isSvg = insideSvg || tag === 'svg';
  const doc = el.ownerDocument;
  const win = doc.defaultView;
  if (!isSvg && win && win.getComputedStyle(el).display === 'none') return null;

  const node: SnapshotNode = { kind: 'element', tag, rect: toRect(el.getBoundingClientRect()) };
  if (isSvg) node.isSvg = true;

  const attrs: Record<string, string> = {};
  for (const attr of Array.from(el.attributes)) {
    const name = attr.name;
    if (name === 'class') {
      if (attr.value.trim()) node.className = attr.value.trim();
      continue;
    }
    if (name === 'data-pv-component-id') {
      node.componentId = attr.value;
      continue;
    }
    if (name === 'data-pv-block') {
      node.pvBlockId = attr.value;
      continue;
    }
    if (name.startsWith('data-pv-loc-app-')) {
      node.locId = name.replace('data-pv-loc-app-', '');
      continue;
    }
    if (isSvg) {
      // Keep every SVG presentation attribute (d, viewBox, fill, …) verbatim;
      // the converter camelCases them for JSX.
      if (!name.startsWith('data-pv-') && !name.startsWith('xlink') && name !== 'xmlns:xlink') {
        attrs[name] = attr.value;
      }
      continue;
    }
    if (isDroppedAttr(name)) continue;
    attrs[name] = attr.value;
  }

  // Form controls: capture the *current* value so the flat copy shows what the
  // user sees on screen, not the initial markup value.
  if (el instanceof HTMLInputElement) {
    if (el.type === 'checkbox' || el.type === 'radio') {
      if (el.checked) attrs['checked'] = 'true';
      else delete attrs['checked'];
    } else if (el.value) {
      attrs['value'] = el.value;
    }
  } else if (el instanceof HTMLTextAreaElement && el.value) {
    attrs['value'] = el.value;
  }

  if (Object.keys(attrs).length > 0) node.attrs = attrs;

  if (node.componentId) {
    counts.set(node.componentId, (counts.get(node.componentId) || 0) + 1);
    const fiber = getFiberComponentProps(el, node.componentId);
    if (fiber) {
      if (Object.keys(fiber.props).length > 0) node.props = fiber.props;
      if (fiber.hasChildren) node.hasChildrenProp = true;
    }
  }

  const children: SnapshotNode[] = [];
  for (const child of Array.from(el.childNodes)) {
    if (child.nodeType === Node.TEXT_NODE) {
      const text = (child.textContent || '').replace(/\s+/g, ' ').trim();
      if (!text) continue;
      const range = doc.createRange();
      range.selectNodeContents(child);
      children.push({ kind: 'text', text, rect: toRect(range.getBoundingClientRect()) });
    } else if (child.nodeType === Node.ELEMENT_NODE) {
      const childNode = walkElement(child as Element, isSvg, counts);
      if (childNode) children.push(childNode);
    }
  }
  if (children.length > 0) node.children = children;

  return node;
}

export function snapshotElement(root: HTMLElement): DomSnapshot | null {
  const counts = new Map<string, number>();
  const rootNode = walkElement(root, false, counts);
  if (!rootNode) return null;
  return {
    root: rootNode,
    foundComponents: Array.from(counts.entries()).map(([componentId, count]) => ({ componentId, count })),
  };
}
