// plugins/protovibe/src/ui/api/specs.ts
// Fetch wrappers for the Specs endpoints (see backend/specs-server.ts).
import type { SpecBundle, SpecItem, SpecSummary, SpecStatus, SpecHeadingLevel } from '../../shared/specs';
import type { SpecExportFormat } from '../../shared/specs-export';

async function postJson<T>(url: string, body: unknown): Promise<T> {
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body ?? {}),
  });
  if (!res.ok) {
    const data = await res.json().catch(() => ({}));
    throw new Error((data as any).error || `Request to ${url} failed`);
  }
  return res.json() as Promise<T>;
}

export async function fetchSpecsList(): Promise<SpecSummary[]> {
  const data = await postJson<{ specs: SpecSummary[] }>('/__specs-list', {});
  return data.specs || [];
}

export async function fetchSpec(specId: string): Promise<SpecBundle> {
  return postJson<SpecBundle>('/__specs-get', { specId });
}

// `id` is pre-generated by the client so spec.json can be snapshotted before it
// exists (undo then deletes the file).
export async function createSpec(id: string, title: string): Promise<SpecBundle> {
  return postJson<SpecBundle>('/__specs-create', { id, title });
}

export async function renameSpec(specId: string, title: string): Promise<SpecBundle> {
  return postJson<SpecBundle>('/__specs-update', { specId, title });
}

export async function deleteSpec(specId: string): Promise<void> {
  await postJson<{ success: boolean }>('/__specs-delete', { specId });
}

export type NewSpecItem =
  | { type: 'heading'; id: string; rank: string; title: string; level: SpecHeadingLevel }
  | {
      type: 'annotation'; id: string; rank: string; text: string;
      status?: SpecStatus | null; state: { tab: 'app'; path: string };
      author: { name: string; email: string };
    };

export async function createSpecItem(params: {
  specId: string;
  item: NewSpecItem;
  /** Present when pinning an annotation to the selected element. */
  file?: string;
  nameEnd?: number[];
}): Promise<SpecBundle & { createdId: string }> {
  return postJson('/__specs-item-create', params);
}

export interface SpecItemPatch {
  /** Headings only. */
  title?: string;
  text?: string;
  /** null clears the status. */
  status?: SpecStatus | null;
  level?: SpecHeadingLevel;
  rank?: string;
  state?: { tab: 'app'; path: string };
}

export async function updateSpecItem(specId: string, itemId: string, patch: SpecItemPatch): Promise<SpecBundle> {
  return postJson<SpecBundle>('/__specs-item-update', { specId, itemId, patch });
}

// Omit file/nameEnd to unpin.
export async function reanchorSpecItem(specId: string, itemId: string, file?: string, nameEnd?: number[]): Promise<SpecBundle> {
  return postJson<SpecBundle>('/__specs-item-reanchor', { specId, itemId, file, nameEnd });
}

export async function deleteSpecItem(specId: string, itemId: string): Promise<SpecBundle> {
  return postJson<SpecBundle>('/__specs-item-delete', { specId, itemId });
}

export async function exportSpec(specId: string, format: SpecExportFormat, publishedUrl: string): Promise<{ content: string; filename: string }> {
  return postJson('/__specs-export', { specId, format, publishedUrl });
}

/**
 * Root of the most recent publish, from protovibe-data.json: the project's main
 * domain (https://<project>.pages.dev) written by the last successful deploy,
 * falling back to the newest per-deploy URL in the history. Empty when the
 * project was never published.
 */
export async function fetchPublishedUrl(): Promise<string> {
  try {
    const res = await fetch('/__cloudflare-publish-metadata', { cache: 'no-store' });
    if (!res.ok) return '';
    const data = await res.json();
    if (typeof data.url === 'string' && data.url.trim()) return data.url.trim().replace(/\/+$/, '');
    const history = Array.isArray(data.deployHistory) ? data.deployHistory : [];
    const latest = history.find((h: unknown) => h && typeof (h as { url?: unknown }).url === 'string' && (h as { url: string }).url.trim());
    return latest ? (latest as { url: string }).url.trim().replace(/\/+$/, '') : '';
  } catch {
    return '';
  }
}

export type { SpecItem };
