// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { PreloaderSpinner } from '@/components/ui/preloader-spinner'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:puwew6 */}
      {/* pv-block-start:7tzslw */}
      <DialogWindow size="xl" data-pv-block="7tzslw" data-pv-sketchpad-el="7tzslw"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:x75tmm */}
          {/* pv-block-start:2gwe6k */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="2gwe6k">
            {/* pv-editable-zone-start:94ubwd */}
              {/* pv-block-start:tb0aj0 */}
              <div data-pv-block="tb0aj0" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:i0v2ao */}
              {/* pv-block-start:n9xnpm */}
              <h2 data-pv-block="n9xnpm" className="text-xl font-semibold text-foreground-default">
              <span></span><span></span>Generate suggested skills in a spreadsheet
              </h2>
              {/* pv-block-end:n9xnpm */}
              {/* pv-block-start:gohxyu */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="gohxyu" typography="regular">
                <span></span><span></span><span></span>Get a template that already has suggested skills matching your positions. <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary hover:opacity-80 transition-opacity">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:gohxyu */}
              {/* pv-editable-zone-end:i0v2ao */}
              </div>
              {/* pv-block-end:tb0aj0 */}
            {/* pv-editable-zone-end:94ubwd */}
          </div>
          {/* pv-block-end:2gwe6k */}
          {/* pv-block-start:mb9rfa */}
          <div data-pv-block="mb9rfa" className="flex flex-col gap-4 items-center py-16 px-5">
            {/* pv-editable-zone-start:tnanie */}
              {/* pv-block-start:f60dt8 */}
              <div className="flex flex-col flex-none bg-[url('/src/images/from-protovibe/sheet-ready-icon-square.svg')] bg-contain bg-center bg-no-repeat aspect-[104/101] w-32" data-pv-block="f60dt8">
                {/* pv-editable-zone-start:rjrcla */}
                {/* pv-editable-zone-end:rjrcla */}
              </div>
              {/* pv-block-end:f60dt8 */}
              {/* pv-block-start:jzpvwl */}
              <div data-pv-block="jzpvwl" className="flex flex-col gap-0">
                {/* pv-editable-zone-start:zx79g1 */}
                {/* pv-block-start:s9j25t */}
                <TextParagraph className="text-center" data-pv-block="s9j25t" typography="bold-primary">
                  <span></span><span></span><span></span>Your spreadsheet is ready
                </TextParagraph>
                {/* pv-block-end:s9j25t */}
                {/* pv-block-start:3q23tv */}
                <TextParagraph className="text-center" data-pv-block="3q23tv" typography="regular">
                  <span></span><span></span><span></span>We grouped your positions into 30 job families and suggested 56 skills
                </TextParagraph>
                {/* pv-block-end:3q23tv */}
                {/* pv-editable-zone-end:zx79g1 */}
              </div>
              {/* pv-block-end:jzpvwl */}
              {/* pv-block-start:ctfod2 */}
              <Button leftIcon="mdi:download" data-pv-block="ctfod2" label="Download file" variant="solid" color="primary" size="md" />
              {/* pv-block-end:ctfod2 */}
            {/* pv-editable-zone-end:tnanie */}
          </div>
          {/* pv-block-end:mb9rfa */}

          {/* pv-block-start:aqb7og */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 py-3 px-5 justify-between" data-pv-block="aqb7og">
            {/* pv-editable-zone-start:94ubwd */}
              {/* pv-block-start:wrud9e */}
              <Button leftIcon="mdi:arrow-left" data-pv-block="wrud9e" label="Back to start" variant="ghost" color="neutral" size="md"  />
              {/* pv-block-end:wrud9e */}

              {/* pv-block-start:vadcyb */}
              <Button leftIcon="mdi:check" data-pv-block="vadcyb" label="Finish and close" variant="ghost" color="neutral" size="md"  />
              {/* pv-block-end:vadcyb */}
            {/* pv-editable-zone-end:94ubwd */}
          </div>
          {/* pv-block-end:aqb7og */}
        {/* pv-editable-zone-end:x75tmm */}
      </DialogWindow>
      {/* pv-block-end:7tzslw */}
      {/* pv-editable-zone-end:puwew6 */}
    </div>
  );
}
