// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:2n7pqy */}
      {/* pv-block-start:sdaeec */}
      <DialogWindow size="xl" data-pv-block="sdaeec" data-pv-sketchpad-el="sdaeec"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:tw6q5w */}
          {/* pv-block-start:9la13c */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="9la13c">
            {/* pv-editable-zone-start:2xmyp4 */}
              {/* pv-block-start:wiwrw5 */}
              <div data-pv-block="wiwrw5" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:dt5pv2 */}
              {/* pv-block-start:sxnnbw */}
              <h2 data-pv-block="sxnnbw" className="text-xl font-semibold text-foreground-default">
              <span></span><span></span>Generate suggested skills in a spreadsheet
              </h2>
              {/* pv-block-end:sxnnbw */}
              {/* pv-block-start:9ay3vt */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="9ay3vt" typography="regular">
                <span></span><span></span><span></span>Get a template that already has suggested skills matching your positions. <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary hover:opacity-80 transition-opacity">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:9ay3vt */}
              {/* pv-editable-zone-end:dt5pv2 */}
              </div>
              {/* pv-block-end:wiwrw5 */}
            {/* pv-editable-zone-end:2xmyp4 */}
          </div>
          {/* pv-block-end:9la13c */}
          {/* pv-block-start:pmsui8 */}
          <div data-pv-block="pmsui8" className="flex flex-col p-5 gap-7">
            {/* pv-editable-zone-start:9fo3ep */}
              {/* pv-block-start:7g6gk1 */}
              <div data-pv-block="7g6gk1" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:or3y0q */}
                {/* pv-block-start:eel6bk */}
                <SuperLabel heading="Which positions would you like to fill with skills?" data-pv-block="eel6bk" primaryText="" />
                {/* pv-block-end:eel6bk */}
                {/* pv-block-start:ldmppg */}
                <MultiSelectDropdown    data-pv-block="ldmppg"  placeholder="Select..." value="all">
                  {/* pv-editable-zone-start:qxnsyn */}
                    {/* pv-block-start:e22vfj */}
                    <SelectDropdownSearch data-pv-block="e22vfj" placeholder="Search people..." />
                    {/* pv-block-end:e22vfj */}
                    {/* pv-block-start:fxw1kv */}
                    <MultiSelectDropdownItem data-pv-block="fxw1kv" value="all" label="All"  />
                    {/* pv-block-end:fxw1kv */}
                    {/* pv-block-start:tluv3b */}
                    <DropdownSeparator data-pv-block="tluv3b" />
                    {/* pv-block-end:tluv3b */}
                    {/* pv-block-start:ms4sjs */}
                    <MultiSelectDropdownItem data-pv-block="ms4sjs" value="2" label="Backend Developer"  />
                    {/* pv-block-end:ms4sjs */}
                    {/* pv-block-start:m1d65b */}
                    <MultiSelectDropdownItem data-pv-block="m1d65b" value="3" label="Senior Backend Developer"  />
                    {/* pv-block-end:m1d65b */}

                    {/* pv-block-start:s64qm4 */}
                    <MultiSelectDropdownItem data-pv-block="s64qm4" value="3" label="Junior Backend Developer"  />
                    {/* pv-block-end:s64qm4 */}

                    {/* pv-block-start:2pmtcf */}
                    <MultiSelectDropdownItem data-pv-block="2pmtcf" value="3" label="Backend Developer"  />
                    {/* pv-block-end:2pmtcf */}

                    {/* pv-block-start:l4twu4 */}
                    <MultiSelectDropdownItem data-pv-block="l4twu4" value="3" label="Junior Front-end Engineer"  />
                    {/* pv-block-end:l4twu4 */}

                    {/* pv-block-start:h6l248 */}
                    <MultiSelectDropdownItem data-pv-block="h6l248" value="3" label="Senior Front-end Engineer"  />
                    {/* pv-block-end:h6l248 */}

                    {/* pv-block-start:r1i4fn */}
                    <MultiSelectDropdownItem data-pv-block="r1i4fn" value="3" label="(...other positions go here)"  />
                    {/* pv-block-end:r1i4fn */}
                  {/* pv-editable-zone-end:qxnsyn */}
                </MultiSelectDropdown>
                {/* pv-block-end:ldmppg */}
                {/* pv-editable-zone-end:or3y0q */}
              </div>
              {/* pv-block-end:7g6gk1 */}

              {/* pv-block-start:fmnn7e */}
              <div data-pv-block="fmnn7e" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:or3y0q */}
                {/* pv-block-start:404k9n */}
                <SuperLabel heading="Which positions would you like to fill with skills?" data-pv-block="404k9n" primaryText="" />
                {/* pv-block-end:404k9n */}
                  {/* pv-block-start:qrdh7f */}
                  <RadioGroup data-pv-block="qrdh7f" orientation="vertical" value="opt1">
                    {/* pv-editable-zone-start:cygyr2 */}
                      {/* pv-block-start:p40mmq */}
                      <RadioItem data-pv-block="p40mmq" value="opt1" primaryText="Yes, fill the template with suggested skills"  />
                      {/* pv-block-end:p40mmq */}
                      {/* pv-block-start:m823s6 */}
                      <RadioItem data-pv-block="m823s6" value="opt2" primaryText="No, get an empty template without example skills"  />
                      {/* pv-block-end:m823s6 */}
                    {/* pv-editable-zone-end:cygyr2 */}
                  </RadioGroup>
                  {/* pv-block-end:qrdh7f */}
                {/* pv-editable-zone-end:or3y0q */}
              </div>
              {/* pv-block-end:fmnn7e */}

              {/* pv-block-start:bb62pi */}
              <div data-pv-block="bb62pi" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:or3y0q */}
                {/* pv-block-start:tfzb3g */}
                <SuperLabel secondaryText="What framework do you prefer?" heading="How many proficiency levels per skill?" data-pv-block="tfzb3g" primaryText="" />
                {/* pv-block-end:tfzb3g */}
                {/* pv-block-start:pvjmg7 */}
                <SelectDropdown className="text-foreground-primary" showClearButton={false} value="opt1"   data-pv-block="pvjmg7" placeholder="Select an option">
                  {/* pv-editable-zone-start:vtz9zr */}
                    {/* pv-block-start:03p0a3 */}
                    <SelectDropdownSearch data-pv-block="03p0a3" placeholder="Search..." />
                    {/* pv-block-end:03p0a3 */}
                    {/* pv-block-start:5ax979 */}
                    <DropdownItem secondaryText="Beginner, Competent, Advanced, Expert" data-pv-block="5ax979" value="opt1" label="Standard 4-level framework" selected={false} />
                    {/* pv-block-end:5ax979 */}
                    {/* pv-block-start:d8tv3a */}
                    <DropdownItem secondaryText="Novice, Beginner, Competent, Proficient, Expert" data-pv-block="d8tv3a" value="opt2" label="Standard 5-level framework" selected={false} />
                    {/* pv-block-end:d8tv3a */}
                    {/* pv-block-start:u04oe5 */}
                    <DropdownItem secondaryText="Your own list of proficiency levels" data-pv-block="u04oe5" value="opt3" label="Custom" selected={false} />
                    {/* pv-block-end:u04oe5 */}
                  {/* pv-editable-zone-end:vtz9zr */}
                </SelectDropdown>
                {/* pv-block-end:pvjmg7 */}
                {/* pv-editable-zone-end:or3y0q */}
              </div>
              {/* pv-block-end:bb62pi */}

              {/* pv-block-start:45ndt1 */}
              <div data-tooltip-text="This section only appears if Custom number of proficiency levels is selected" data-pv-block="45ndt1" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:or3y0q */}
                {/* pv-block-start:8gfm24 */}
                <SuperLabel secondaryText="A lower number indicates a lower level." heading="Custom proficiency levels" data-pv-block="8gfm24" primaryText="" />
                {/* pv-block-end:8gfm24 */}
                {/* pv-block-start:4v3qaz */}
                <div className="flex min-h-4 flex-row items-center justify-start gap-1" data-pv-block="4v3qaz">
                  {/* pv-editable-zone-start:w2v43y */}
                    {/* pv-block-start:lhwc6d */}
                    <Icon data-pv-block="lhwc6d" iconSymbol="mdi:drag-vertical" size="lg" />
                    {/* pv-block-end:lhwc6d */}
                    {/* pv-block-start:mk878m */}
                    <div className="flex flex-col min-h-4 text-center leading-none items-center justify-center w-6 h-6 rounded-full bg-background-primary-subtle text-foreground-secondary text-sm font-semibold mr-1" data-pv-block="mk878m">
                      {/* pv-editable-zone-start:lczuef */}
                        {/* pv-block-start:17ktzk */}
                        <span data-pv-block="17ktzk">
                          1
                        </span>
                        {/* pv-block-end:17ktzk */}
                      {/* pv-editable-zone-end:lczuef */}
                    </div>
                    {/* pv-block-end:mk878m */}
                    {/* pv-block-start:4zmjbv */}
                    <Input data-pv-block="4zmjbv" placeholder="Proficiency level name, e.g. Beginner" />
                    {/* pv-block-end:4zmjbv */}
                    {/* pv-block-start:bpfr6l */}
                    <Button leftIcon="mdi:close" iconOnly data-pv-block="bpfr6l" label="Button" variant="ghost" color="neutral" size="md" />
                    {/* pv-block-end:bpfr6l */}
                  {/* pv-editable-zone-end:w2v43y */}
                </div>
                {/* pv-block-end:4v3qaz */}

                {/* pv-block-start:e2l3o6 */}
                <div className="flex min-h-4 flex-row items-center justify-start gap-1" data-pv-block="e2l3o6">
                  {/* pv-editable-zone-start:w2v43y */}
                    {/* pv-block-start:rr3pxh */}
                    <Icon data-pv-block="rr3pxh" iconSymbol="mdi:drag-vertical" size="lg" />
                    {/* pv-block-end:rr3pxh */}
                    {/* pv-block-start:p533ek */}
                    <div className="flex flex-col min-h-4 text-center leading-none items-center justify-center w-6 h-6 rounded-full bg-background-primary-subtle text-foreground-secondary text-sm font-semibold mr-1" data-pv-block="p533ek">
                      {/* pv-editable-zone-start:lczuef */}
                        {/* pv-block-start:y2ft84 */}
                        <span data-pv-block="y2ft84">
                          2
                        </span>
                        {/* pv-block-end:y2ft84 */}
                      {/* pv-editable-zone-end:lczuef */}
                    </div>
                    {/* pv-block-end:p533ek */}
                    {/* pv-block-start:rutske */}
                    <Input data-pv-block="rutske" placeholder="Proficiency level name, e.g. Beginner" />
                    {/* pv-block-end:rutske */}
                    {/* pv-block-start:eeww6b */}
                    <Button leftIcon="mdi:close" iconOnly data-pv-block="eeww6b" label="Button" variant="ghost" color="neutral" size="md" />
                    {/* pv-block-end:eeww6b */}
                  {/* pv-editable-zone-end:w2v43y */}
                </div>
                {/* pv-block-end:e2l3o6 */}

                {/* pv-block-start:iusjyg */}
                <div className="flex min-h-4 flex-row items-center justify-start gap-1" data-pv-block="iusjyg">
                  {/* pv-editable-zone-start:w2v43y */}
                    {/* pv-block-start:w73vbh */}
                    <Icon data-pv-block="w73vbh" iconSymbol="mdi:drag-vertical" size="lg" />
                    {/* pv-block-end:w73vbh */}
                    {/* pv-block-start:r2su0r */}
                    <div className="flex flex-col min-h-4 text-center leading-none items-center justify-center w-6 h-6 rounded-full bg-background-primary-subtle text-foreground-secondary text-sm font-semibold mr-1" data-pv-block="r2su0r">
                      {/* pv-editable-zone-start:lczuef */}
                        {/* pv-block-start:y0lcl7 */}
                        <span data-pv-block="y0lcl7">
                          3
                        </span>
                        {/* pv-block-end:y0lcl7 */}
                      {/* pv-editable-zone-end:lczuef */}
                    </div>
                    {/* pv-block-end:r2su0r */}
                    {/* pv-block-start:oain13 */}
                    <Input data-pv-block="oain13" placeholder="Proficiency level name, e.g. Beginner" />
                    {/* pv-block-end:oain13 */}
                    {/* pv-block-start:6i3uho */}
                    <Button leftIcon="mdi:close" iconOnly data-pv-block="6i3uho" label="Button" variant="ghost" color="neutral" size="md" />
                    {/* pv-block-end:6i3uho */}
                  {/* pv-editable-zone-end:w2v43y */}
                </div>
                {/* pv-block-end:iusjyg */}
                {/* pv-editable-zone-end:or3y0q */}
              </div>
              {/* pv-block-end:45ndt1 */}

              {/* pv-block-start:y84j4i */}
              <div data-pv-block="y84j4i" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:or3y0q */}
                {/* pv-block-start:ra8wjw */}
                <SuperLabel secondaryText="For example, what methodologies you plan to use, what industry you’re in." heading="Additonal instructions for AI" data-pv-block="ra8wjw" primaryText="" />
                {/* pv-block-end:ra8wjw */}
                {/* pv-block-start:fxmbq4 */}
                <Textarea data-pv-block="fxmbq4" placeholder="Optional" />
                {/* pv-block-end:fxmbq4 */}
                {/* pv-editable-zone-end:or3y0q */}
              </div>
              {/* pv-block-end:y84j4i */}
            {/* pv-editable-zone-end:9fo3ep */}
          </div>
          {/* pv-block-end:pmsui8 */}

          {/* pv-block-start:1a6f2n */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 justify-end py-3 px-5" data-pv-block="1a6f2n">
            {/* pv-editable-zone-start:2xmyp4 */}
              {/* pv-block-start:vsdapq */}
              <div data-pv-block="vsdapq" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:e2sff4 */}
                {/* pv-block-start:kig1wi */}
                <Button data-pv-block="kig1wi" label="Cancel" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:kig1wi */}
                {/* pv-block-start:0z0827 */}
                <Button rightIcon="mdi:arrow-right" data-pv-block="0z0827" label="Generate file" variant="solid" color="primary" size="md"  />
                {/* pv-block-end:0z0827 */}
                {/* pv-editable-zone-end:e2sff4 */}
              </div>
              {/* pv-block-end:vsdapq */}
            {/* pv-editable-zone-end:2xmyp4 */}
          </div>
          {/* pv-block-end:1a6f2n */}
        {/* pv-editable-zone-end:tw6q5w */}
      </DialogWindow>
      {/* pv-block-end:sdaeec */}
      {/* pv-editable-zone-end:2n7pqy */}
    </div>
  );
}
