// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { PreloaderSpinner } from '@/components/ui/preloader-spinner'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:xverg2 */}
      {/* pv-block-start:pamzt2 */}
      <DialogWindow size="xl" data-pv-block="pamzt2" data-pv-sketchpad-el="pamzt2"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:qwbcbc */}
          {/* pv-block-start:t9kscq */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="t9kscq">
            {/* pv-editable-zone-start:38zx36 */}
              {/* pv-block-start:3nf5lh */}
              <div data-pv-block="3nf5lh" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:2s35ui */}
              {/* pv-block-start:8fber7 */}
              <h2 data-pv-block="8fber7" className="text-xl font-semibold text-foreground-default">
                <span></span><span></span><span></span>Import skills to positions from a file
              </h2>
              {/* pv-block-end:8fber7 */}
              {/* pv-block-start:hhaij0 */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="hhaij0" typography="regular">
                <span></span><span></span><span></span>Upload your document and AI will read it and import skills to Tellent HR. <a className="text-foreground-primary hover:opacity-80 transition-opacity" href="https://" target="_blank" rel="noopener noreferrer">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:hhaij0 */}
              {/* pv-editable-zone-end:2s35ui */}
              </div>
              {/* pv-block-end:3nf5lh */}
            {/* pv-editable-zone-end:38zx36 */}
          </div>
          {/* pv-block-end:t9kscq */}
          {/* pv-block-start:12g8us */}
          <div data-pv-block="12g8us" className="flex flex-col gap-4 items-center p-5">
            {/* pv-editable-zone-start:1lwlgc */}
              {/* pv-block-start:ckg5l1 */}
              <div data-pv-block="ckg5l1" className="flex flex-col gap-2 pt-4 justify-center min-h-72">
                {/* pv-editable-zone-start:o1rs2a */}
                {/* pv-block-start:gerekd */}
                <PreloaderSpinner data-pv-block="gerekd" size="xl" />
                {/* pv-block-end:gerekd */}
                {/* pv-block-start:zb0716 */}
                <div data-pv-block="zb0716" className="flex flex-col gap-0">
                  {/* pv-editable-zone-start:xbptpy */}
                  {/* pv-block-start:04acs2 */}
                  <TextParagraph className="text-center" data-pv-block="04acs2" typography="bold-primary">
                    <span></span><span></span><span></span>Creating skills and assigning positions...
                  </TextParagraph>
                  {/* pv-block-end:04acs2 */}
                  {/* pv-block-start:icz2gj */}
                  <TextParagraph className="text-center" data-pv-block="icz2gj" typography="regular">
                    <span></span><span></span><span></span>Please wait...
                  </TextParagraph>
                  {/* pv-block-end:icz2gj */}
                  {/* pv-editable-zone-end:xbptpy */}
                </div>
                {/* pv-block-end:zb0716 */}
                {/* pv-editable-zone-end:o1rs2a */}
              </div>
              {/* pv-block-end:ckg5l1 */}
            {/* pv-editable-zone-end:1lwlgc */}
          </div>
          {/* pv-block-end:12g8us */}
        {/* pv-editable-zone-end:qwbcbc */}
      </DialogWindow>
      {/* pv-block-end:pamzt2 */}
      {/* pv-editable-zone-end:xverg2 */}
    </div>
  );
}
