// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { PreloaderSpinner } from '@/components/ui/preloader-spinner'
import { TextHeading } from '@/components/ui/text-heading'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:rwi9sz */}
      {/* pv-block-start:iic05m */}
      <DialogWindow size="lg" data-pv-block="iic05m" data-pv-sketchpad-el="iic05m"  style={{ position: 'absolute', left: 417, top: 148 }}>
        {/* pv-editable-zone-start:lgeu7v */}
          {/* pv-block-start:6sjda0 */}
          <div data-pv-block="6sjda0" className="flex flex-col items-center py-16 px-5 gap-8">
            {/* pv-editable-zone-start:q2vvul */}
              {/* pv-block-start:dce4pv */}
              <div className="flex flex-col flex-none bg-contain bg-center bg-no-repeat w-32 bg-[url('/src/images/from-protovibe/success-icon.svg')] aspect-[1/1]" data-pv-block="dce4pv">
                {/* pv-editable-zone-start:8zn1i0 */}
                {/* pv-editable-zone-end:8zn1i0 */}
              </div>
              {/* pv-block-end:dce4pv */}
              {/* pv-block-start:nosa3g */}
              <div data-pv-block="nosa3g" className="flex flex-col gap-0">
                {/* pv-editable-zone-start:gm5zy0 */}
                {/* pv-block-start:fcg1vl */}
                <TextHeading className="text-center" data-pv-block="fcg1vl" typography="heading-lg">
                  <span></span><span></span>Skills added!
                </TextHeading>
                {/* pv-block-end:fcg1vl */}
                {/* pv-block-start:hiealy */}
                <TextParagraph className="text-center" data-pv-block="hiealy" typography="secondary">
                  <span></span><span></span><span></span>Succesfully imported 32 skills to 45 positions.
                </TextParagraph>
                {/* pv-block-end:hiealy */}
                {/* pv-editable-zone-end:gm5zy0 */}
              </div>
              {/* pv-block-end:nosa3g */}
              {/* pv-block-start:g26kql */}
              <div data-pv-block="g26kql" className="flex flex-col gap-2 min-w-48">
                {/* pv-editable-zone-start:66mq54 */}
                {/* pv-block-start:y0z2d1 */}
                <Button leftIcon="mdi:external-link" data-pv-block="y0z2d1" label="Give feedback" variant="outline" color="neutral" size="md" />
                {/* pv-block-end:y0z2d1 */}
                {/* pv-block-start:aviqc7 */}
                <Button leftIcon="" data-pv-block="aviqc7" label="Finish and close" variant="solid" color="primary" size="md" />
                {/* pv-block-end:aviqc7 */}
                {/* pv-editable-zone-end:66mq54 */}
              </div>
              {/* pv-block-end:g26kql */}
            {/* pv-editable-zone-end:q2vvul */}
          </div>
          {/* pv-block-end:6sjda0 */}
        {/* pv-editable-zone-end:lgeu7v */}
      </DialogWindow>
      {/* pv-block-end:iic05m */}
      {/* pv-editable-zone-end:rwi9sz */}
    </div>
  );
}
