// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:dpo0vh */}
      {/* pv-block-start:li8oi4 */}
      <DialogWindow size="xl" data-pv-block="li8oi4" data-pv-sketchpad-el="li8oi4"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:wzj4f3 */}
          {/* pv-block-start:awni33 */}
          <div data-pv-block="awni33" className="flex flex-col gap-2 p-12">
            {/* pv-editable-zone-start:d1m5f2 */}
              {/* pv-block-start:ootyxe */}
              <div data-pv-block="ootyxe" className="flex flex-row items-start gap-16">
                {/* pv-editable-zone-start:fr3dox */}
                {/* pv-block-start:hv7kpz */}
                <div data-pv-block="hv7kpz" className="flex flex-col gap-8">
                {/* pv-editable-zone-start:p6xn0l */}
                {/* pv-block-start:p9p37g */}
                <div data-pv-block="p9p37g" className="flex flex-col gap-4">
                {/* pv-editable-zone-start:36283e */}
                {/* pv-block-start:setiw2 */}
                <h2 data-pv-block="setiw2" className="font-semibold text-foreground-default text-2xl">
                <span></span><span></span>Generate suggested skills in a spreadsheet
                </h2>
                {/* pv-block-end:setiw2 */}
                {/* pv-editable-zone-end:36283e */}
                </div>
                {/* pv-block-end:p9p37g */}
                {/* pv-block-start:0iw2xd */}
                <div data-pv-block="0iw2xd" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:qldj8q */}
                {/* pv-block-start:ams851 */}
                <div className="flex flex-col items-start relative pb-6 min-h-16" data-pv-block="ams851">
                {/* pv-editable-zone-start:28v94v */}
                {/* pv-block-start:xwxd9r */}
                <div data-pv-block="xwxd9r" className="flex flex-row items-start justify-start gap-3">
                {/* pv-editable-zone-start:d46es7 */}
                {/* pv-block-start:s1q6p4 */}
                <StepCircle data-pv-block="s1q6p4" state="current" number={1} />
                {/* pv-block-end:s1q6p4 */}
                {/* pv-block-start:43mq4n */}
                <div data-pv-block="43mq4n" className="flex flex-col gap-0">
                  {/* pv-editable-zone-start:fq7vb3 */}
                  {/* pv-block-start:d58yn8 */}
                  <TextParagraph className="pt-0.5" data-pv-block="d58yn8" typography="bold-primary">
                    <span></span><span></span><span></span>Upload a file with company skills
                  </TextParagraph>
                  {/* pv-block-end:d58yn8 */}
                  {/* pv-block-start:zwj3hr */}
                  <TextParagraph className="pt-0.5" data-pv-block="zwj3hr" typography="regular">
                    <span></span>Don’t have a document that defines skills in your company yet? No worries, we can help you kick-off this project!
                  </TextParagraph>
                  {/* pv-block-end:zwj3hr */}
                  {/* pv-editable-zone-end:fq7vb3 */}
                </div>
                {/* pv-block-end:43mq4n */}

                {/* pv-editable-zone-end:d46es7 */}
                </div>
                {/* pv-block-end:xwxd9r */}
                
                  {/* pv-block-start:coqa5y */}
                  <div className="flex flex-col w-6 items-center absolute top-8 bottom-0 min-h-2" data-pv-block="coqa5y">
                    {/* pv-editable-zone-start:t0aqsx */}
                      {/* pv-block-start:h89lcx */}
                      <div className="flex flex-col min-h-4 w-px bg-background-primary flex-1" data-pv-block="h89lcx">
                        {/* pv-editable-zone-start:m6ovhb */}
                        {/* pv-editable-zone-end:m6ovhb */}
                      </div>
                      {/* pv-block-end:h89lcx */}
                    {/* pv-editable-zone-end:t0aqsx */}
                  </div>
                  {/* pv-block-end:coqa5y */}
                {/* pv-editable-zone-end:28v94v */}
                </div>
                {/* pv-block-end:ams851 */}

                {/* pv-block-start:y2ez92 */}
                <div className="flex flex-col items-start relative pb-6 min-h-16" data-pv-block="y2ez92">
                {/* pv-editable-zone-start:q67k1c */}
                {/* pv-block-start:rt83ku */}
                <div data-pv-block="rt83ku" className="flex flex-row items-start justify-start gap-3">
                {/* pv-editable-zone-start:d46es7 */}
                {/* pv-block-start:rj843c */}
                <StepCircle data-pv-block="rj843c" state="current" number={1} />
                {/* pv-block-end:rj843c */}
                {/* pv-block-start:4fmsib */}
                <div data-pv-block="4fmsib" className="flex flex-col gap-0">
                  {/* pv-editable-zone-start:fq7vb3 */}
                  {/* pv-block-start:gtwskv */}
                  <TextParagraph className="pt-0.5" data-pv-block="gtwskv" typography="bold-primary">
                    <span></span><span></span><span></span>Preview
                  </TextParagraph>
                  {/* pv-block-end:gtwskv */}
                  {/* pv-block-start:v40yil */}
                  <TextParagraph className="pt-0.5" data-pv-block="v40yil" typography="regular">
                    <span></span><span></span><span></span>See list of skills and positions before applying changes
                  </TextParagraph>
                  {/* pv-block-end:v40yil */}
                  {/* pv-editable-zone-end:fq7vb3 */}
                </div>
                {/* pv-block-end:4fmsib */}
                {/* pv-editable-zone-end:d46es7 */}
                </div>
                {/* pv-block-end:rt83ku */}
                
                  {/* pv-block-start:o5x116 */}
                  <div className="flex flex-col w-6 items-center absolute top-8 bottom-0 min-h-2" data-pv-block="o5x116">
                    {/* pv-editable-zone-start:o8hlnf */}
                      {/* pv-block-start:s3avan */}
                      <div className="flex flex-col min-h-4 w-px bg-background-primary flex-1" data-pv-block="s3avan">
                        {/* pv-editable-zone-start:9z3crc */}
                        {/* pv-editable-zone-end:9z3crc */}
                      </div>
                      {/* pv-block-end:s3avan */}
                    {/* pv-editable-zone-end:o8hlnf */}
                  </div>
                  {/* pv-block-end:o5x116 */}
                {/* pv-editable-zone-end:q67k1c */}
                </div>
                {/* pv-block-end:y2ez92 */}

                {/* pv-block-start:bjkghv */}
                <div className="flex flex-col items-start relative pb-6 min-h-0" data-pv-block="bjkghv">
                {/* pv-editable-zone-start:no8bze */}
                {/* pv-block-start:lwkw3n */}
                <div data-pv-block="lwkw3n" className="flex flex-row items-start justify-start gap-3">
                {/* pv-editable-zone-start:d46es7 */}
                {/* pv-block-start:luha31 */}
                <StepCircle data-pv-block="luha31" state="current" number={1} />
                {/* pv-block-end:luha31 */}
                {/* pv-block-start:hb42kq */}
                <div data-pv-block="hb42kq" className="flex flex-col gap-0">
                  {/* pv-editable-zone-start:fq7vb3 */}
                  {/* pv-block-start:l4gbx4 */}
                  <TextParagraph className="pt-0.5" data-pv-block="l4gbx4" typography="bold-primary">
                    <span></span><span></span><span></span>Apply changes
                  </TextParagraph>
                  {/* pv-block-end:l4gbx4 */}
                  {/* pv-block-start:6yh4hz */}
                  <TextParagraph className="pt-0.5" data-pv-block="6yh4hz" typography="regular">
                    <span></span><span></span><span></span>Confirm and import skills
                  </TextParagraph>
                  {/* pv-block-end:6yh4hz */}
                  {/* pv-editable-zone-end:fq7vb3 */}
                </div>
                {/* pv-block-end:hb42kq */}
                {/* pv-editable-zone-end:d46es7 */}
                </div>
                {/* pv-block-end:lwkw3n */}
                
                  {/* pv-block-start:vv977q */}
                  <div className="flex-col w-6 items-center absolute top-8 bottom-0 min-h-2 hidden" data-pv-block="vv977q">
                    {/* pv-editable-zone-start:e1g3qj */}
                      {/* pv-block-start:o01glc */}
                      <div className="flex flex-col min-h-4 w-px bg-background-primary flex-1" data-pv-block="o01glc">
                        {/* pv-editable-zone-start:kv9s12 */}
                        {/* pv-editable-zone-end:kv9s12 */}
                      </div>
                      {/* pv-block-end:o01glc */}
                    {/* pv-editable-zone-end:e1g3qj */}
                  </div>
                  {/* pv-block-end:vv977q */}
                {/* pv-editable-zone-end:no8bze */}
                </div>
                {/* pv-block-end:bjkghv */}
                {/* pv-editable-zone-end:qldj8q */}
                </div>
                {/* pv-block-end:0iw2xd */}
                {/* pv-editable-zone-end:p6xn0l */}
                </div>
                {/* pv-block-end:hv7kpz */}
                {/* pv-block-start:tqgkud */}
                <Image data-pv-block="tqgkud" className="bg-cover bg-center bg-no-repeat w-full bg-[url('/src/images/from-protovibe/ai-skills-illustration.svg')] aspect-[314/371] max-w-[323px]" />
                {/* pv-block-end:tqgkud */}
                {/* pv-editable-zone-end:fr3dox */}
              </div>
              {/* pv-block-end:ootyxe */}
            {/* pv-editable-zone-end:d1m5f2 */}
          </div>
          {/* pv-block-end:awni33 */}
          {/* pv-block-start:axe22k */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 justify-between py-3 px-5" data-pv-block="axe22k">
            {/* pv-editable-zone-start:8etqlx */}
              {/* pv-block-start:v19je1 */}
              <Checkbox data-pv-block="v19je1" primaryText="Don't show this intro again" />
              {/* pv-block-end:v19je1 */}
              {/* pv-block-start:xw3vxw */}
              <div data-pv-block="xw3vxw" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:hspybn */}
                {/* pv-block-start:iefp1d */}
                <Button data-pv-block="iefp1d" label="Cancel" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:iefp1d */}
                {/* pv-block-start:evqex1 */}
                <Button rightIcon="mdi:arrow-right" data-pv-block="evqex1" label="Let's start" variant="solid" color="primary" size="md"  />
                {/* pv-block-end:evqex1 */}
                {/* pv-editable-zone-end:hspybn */}
              </div>
              {/* pv-block-end:xw3vxw */}
            {/* pv-editable-zone-end:8etqlx */}
          </div>
          {/* pv-block-end:axe22k */}
        {/* pv-editable-zone-end:wzj4f3 */}
      </DialogWindow>
      {/* pv-block-end:li8oi4 */}
      {/* pv-editable-zone-end:dpo0vh */}
    </div>
  );
}
