// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { PreloaderSpinner } from '@/components/ui/preloader-spinner'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:ercway */}
      {/* pv-block-start:4e1bxy */}
      <DialogWindow size="xl" data-pv-block="4e1bxy" data-pv-sketchpad-el="4e1bxy"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:bkrv6t */}
          {/* pv-block-start:9hly6q */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="9hly6q">
            {/* pv-editable-zone-start:wdklis */}
              {/* pv-block-start:t5mn6q */}
              <div data-pv-block="t5mn6q" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:gu1d0k */}
              {/* pv-block-start:6ysty8 */}
              <h2 data-pv-block="6ysty8" className="text-xl font-semibold text-foreground-default">
              <span></span><span></span>Generate suggested skills in a spreadsheet
              </h2>
              {/* pv-block-end:6ysty8 */}
              {/* pv-block-start:7sypun */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="7sypun" typography="regular">
                <span></span><span></span><span></span>Get a template that already has suggested skills matching your positions. <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary hover:opacity-80 transition-opacity">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:7sypun */}
              {/* pv-editable-zone-end:gu1d0k */}
              </div>
              {/* pv-block-end:t5mn6q */}
            {/* pv-editable-zone-end:wdklis */}
          </div>
          {/* pv-block-end:9hly6q */}
          {/* pv-block-start:032m3g */}
          <div data-pv-block="032m3g" className="flex flex-col gap-4 items-center p-5">
            {/* pv-editable-zone-start:pwrm31 */}
              {/* pv-block-start:iq5pnn */}
              <div data-pv-block="iq5pnn" className="flex flex-col gap-2 pt-4">
                {/* pv-editable-zone-start:23nmht */}
                {/* pv-block-start:wae0ho */}
                <PreloaderSpinner data-pv-block="wae0ho" size="xl" />
                {/* pv-block-end:wae0ho */}
                {/* pv-block-start:twwrwu */}
                <div data-pv-block="twwrwu" className="flex flex-col gap-0">
                  {/* pv-editable-zone-start:rcg384 */}
                  {/* pv-block-start:oy0e3w */}
                  <TextParagraph className="text-center" data-pv-block="oy0e3w" typography="bold-primary">
                    <span></span><span></span>Analysing your positions...
                  </TextParagraph>
                  {/* pv-block-end:oy0e3w */}
                  {/* pv-block-start:czuex1 */}
                  <TextParagraph className="text-center" data-pv-block="czuex1" typography="regular">
                    <span></span><span></span><span></span>It will take about 30 seconds. In the meantime your can play the game below.
                  </TextParagraph>
                  {/* pv-block-end:czuex1 */}
                  {/* pv-editable-zone-end:rcg384 */}
                </div>
                {/* pv-block-end:twwrwu */}
                {/* pv-editable-zone-end:23nmht */}
              </div>
              {/* pv-block-end:iq5pnn */}



              {/* pv-block-start:kzpqe8 */}
              <div className="flex flex-col min-h-32 w-full px-8 h-72" data-pv-block="kzpqe8">
                {/* pv-editable-zone-start:s73jd2 */}
                {/* pv-block-start:m7n2p9 */}
                <iframe
                  data-pv-block="m7n2p9"
                  src="https://thriving-bombolone-1cfc2b.netlify.app/"
                  className="w-full h-full"
                  frameBorder="0"
                />
                {/* pv-block-end:m7n2p9 */}
                {/* pv-editable-zone-end:s73jd2 */}
              </div>
              {/* pv-block-end:kzpqe8 */}
            {/* pv-editable-zone-end:pwrm31 */}
          </div>
          {/* pv-block-end:032m3g */}

          {/* pv-block-start:2j5her */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 py-3 px-5 justify-start" data-pv-block="2j5her">
            {/* pv-editable-zone-start:wdklis */}
              {/* pv-block-start:rbnqt4 */}
              <div data-pv-block="rbnqt4" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:ekn2l6 */}
                {/* pv-block-start:qrvgeo */}
                <Button leftIcon="mdi:arrow-left" data-pv-block="qrvgeo" label="Back" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:qrvgeo */}
                {/* pv-editable-zone-end:ekn2l6 */}
              </div>
              {/* pv-block-end:rbnqt4 */}
            {/* pv-editable-zone-end:wdklis */}
          </div>
          {/* pv-block-end:2j5her */}
        {/* pv-editable-zone-end:bkrv6t */}
      </DialogWindow>
      {/* pv-block-end:4e1bxy */}
      {/* pv-editable-zone-end:ercway */}
    </div>
  );
}
