// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { Card } from '@/components/ui/card'
import { Stepper } from '@/components/ui/stepper'
import { StepperConnector } from '@/components/ui/stepper-connector'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:gl1yla */}
      {/* pv-block-start:cs131a */}
      <DialogWindow size="xl" data-pv-block="cs131a" data-pv-sketchpad-el="cs131a"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:mi0z44 */}
          {/* pv-block-start:657op2 */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="657op2">
            {/* pv-editable-zone-start:t7nd3c */}
              {/* pv-block-start:1qh7o4 */}
              <div data-pv-block="1qh7o4" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:7l5x7c */}
              {/* pv-block-start:q0aexa */}
              <h2 data-pv-block="q0aexa" className="text-xl font-semibold text-foreground-default">
                <span></span><span></span><span></span>Import skills to positions from a file
              </h2>
              {/* pv-block-end:q0aexa */}
              {/* pv-block-start:utdpi0 */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="utdpi0" typography="regular">
                <span></span><span></span><span></span>Upload your document and AI will read it and import skills to Tellent HR. <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary hover:opacity-80 transition-opacity">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:utdpi0 */}
              {/* pv-editable-zone-end:7l5x7c */}
              </div>
              {/* pv-block-end:1qh7o4 */}
            {/* pv-editable-zone-end:t7nd3c */}
          </div>
          {/* pv-block-end:657op2 */}
          {/* pv-block-start:8vzh4t */}
          <div data-pv-block="8vzh4t" className="flex flex-col p-5 gap-7">
            {/* pv-editable-zone-start:zzgb3q */}
              {/* pv-block-start:inbixm */}
              <Stepper data-pv-block="inbixm" fullWidth={false}>
                {/* pv-editable-zone-start:v4z32l */}
                  {/* pv-block-start:j2037q */}
                  <StepCircle labelPosition="right" data-pv-block="j2037q" state="current" number={1} label="Upload file" />
                  {/* pv-block-end:j2037q */}
                  {/* pv-block-start:prdr4d */}
                  <StepperConnector data-pv-block="prdr4d" state="upcoming" />
                  {/* pv-block-end:prdr4d */}
                  {/* pv-block-start:b1mzqk */}
                  <StepCircle labelPosition="right" data-pv-block="b1mzqk" state="upcoming" number={2} label="Preview skills" />
                  {/* pv-block-end:b1mzqk */}
                  {/* pv-block-start:9r4yey */}
                  <StepperConnector data-pv-block="9r4yey" state="upcoming" />
                  {/* pv-block-end:9r4yey */}
                  {/* pv-block-start:tsf3yd */}
                  <StepCircle labelPosition="right" data-pv-block="tsf3yd" state="upcoming" number={3} label="Apply changes" />
                  {/* pv-block-end:tsf3yd */}
                {/* pv-editable-zone-end:v4z32l */}
              </Stepper>
              {/* pv-block-end:inbixm */}
              {/* pv-block-start:gi7tw3 */}
              <div data-pv-block="gi7tw3" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:z2ub36 */}
                {/* pv-block-start:6qscpx */}
                <SuperLabel secondaryText="Supported file formats: PDF, DOCX, CSV or XLSX • Max. file size: 5 MB" heading="Upload files with skills" data-pv-block="6qscpx" primaryText="" />
                {/* pv-block-end:6qscpx */}
                {/* pv-block-start:qyad0c */}
                <Card className="gap-1 p-3 flex-row items-center" data-pv-block="qyad0c">
                  {/* pv-editable-zone-start:pgd735 */}
                    {/* pv-block-start:d6c1v4 */}
                    <Icon data-pv-block="d6c1v4" iconSymbol="mdi:file-text" size="md" />
                    {/* pv-block-end:d6c1v4 */}
                    {/* pv-block-start:k5n3e5 */}
                    <TextParagraph className="flex-1" data-pv-block="k5n3e5" typography="regular">
                      <span></span><span></span>company skills final (use this version) v1 (recovered).docx
                    </TextParagraph>
                    {/* pv-block-end:k5n3e5 */}
                    {/* pv-block-start:kqeyjl */}
                    <Button leftIcon="mdi:close" iconOnly data-pv-block="kqeyjl" label="Button" variant="ghost" color="neutral" size="md" />
                    {/* pv-block-end:kqeyjl */}
                  {/* pv-editable-zone-end:pgd735 */}
                </Card>
                {/* pv-block-end:qyad0c */}
                {/* pv-block-start:xl24qo */}
                <Button leftIcon="mdi:upload" className="self-start" data-pv-block="xl24qo" label="Upload more files" variant="outline" color="neutral" size="sm" />
                {/* pv-block-end:xl24qo */}
                {/* pv-editable-zone-end:z2ub36 */}
              </div>
              {/* pv-block-end:gi7tw3 */}

              {/* pv-block-start:5t0e9k */}
              <div data-tooltip-text="This section only appears if Custom number of proficiency levels is selected" data-pv-block="5t0e9k" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:karvkw */}
                {/* pv-block-start:98fw46 */}
                <SuperLabel secondaryText="To ensure best quality, instruct AI what to expect in your file" heading="What's in your file?" data-pv-block="98fw46" primaryText="" />
                {/* pv-block-end:98fw46 */}
                {/* pv-block-start:jb66tm */}
                <Card className="gap-1 p-3" data-pv-block="jb66tm">
                  {/* pv-editable-zone-start:pgd735 */}
                    {/* pv-block-start:p71vtz */}
                    <Checkbox data-pv-block="p71vtz" primaryText="Skills have a unique name and description" />
                    {/* pv-block-end:p71vtz */}

                    {/* pv-block-start:vqsgx0 */}
                    <Checkbox data-pv-block="vqsgx0" primaryText="Skills have proficiency levels (e.g. ‘Beginner’, ‘Intermediate’, ‘Expert’ or ‘P1’, ‘P2’, ‘P3’)" />
                    {/* pv-block-end:vqsgx0 */}

                    {/* pv-block-start:nfh43p */}
                    <Checkbox data-pv-block="nfh43p" primaryText="Each proficiency level have a description what is expected" />
                    {/* pv-block-end:nfh43p */}

                    {/* pv-block-start:ttmtb2 */}
                    <Checkbox data-pv-block="ttmtb2" primaryText="Positions are associated with a skill and its proficiency level" />
                    {/* pv-block-end:ttmtb2 */}

                    {/* pv-block-start:287n40 */}
                    <Checkbox data-pv-block="287n40" primaryText="Skills are grouped into categories (such as ‘Soft skills” or ‘Technical skills’)" />
                    {/* pv-block-end:287n40 */}
                  {/* pv-editable-zone-end:pgd735 */}
                </Card>
                {/* pv-block-end:jb66tm */}
                {/* pv-editable-zone-end:karvkw */}
              </div>
              {/* pv-block-end:5t0e9k */}

              {/* pv-block-start:f6ckmi */}
              <div data-pv-block="f6ckmi" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:karvkw */}
                {/* pv-block-start:jvujl1 */}
                <SuperLabel secondaryText="For example, what methodologies you plan to use, what industry you’re in." heading="Additonal instructions for AI" data-pv-block="jvujl1" primaryText="" />
                {/* pv-block-end:jvujl1 */}
                {/* pv-block-start:vesrkd */}
                <Textarea data-pv-block="vesrkd" placeholder="Optional" />
                {/* pv-block-end:vesrkd */}
                {/* pv-editable-zone-end:karvkw */}
              </div>
              {/* pv-block-end:f6ckmi */}
            {/* pv-editable-zone-end:zzgb3q */}
          </div>
          {/* pv-block-end:8vzh4t */}

          {/* pv-block-start:bvrioh */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 justify-end py-3 px-5" data-pv-block="bvrioh">
            {/* pv-editable-zone-start:zbrnm6 */}
              {/* pv-block-start:f42yvj */}
              <div data-pv-block="f42yvj" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:mllxfs */}
                {/* pv-block-start:o0h153 */}
                <Button data-pv-block="o0h153" label="Cancel" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:o0h153 */}
                {/* pv-block-start:ke0plm */}
                <Button rightIcon="mdi:arrow-right" data-pv-block="ke0plm" label="Continue" variant="solid" color="primary" size="md"  />
                {/* pv-block-end:ke0plm */}
                {/* pv-editable-zone-end:mllxfs */}
              </div>
              {/* pv-block-end:f42yvj */}
            {/* pv-editable-zone-end:zbrnm6 */}
          </div>
          {/* pv-block-end:bvrioh */}
        {/* pv-editable-zone-end:mi0z44 */}
      </DialogWindow>
      {/* pv-block-end:cs131a */}
      {/* pv-editable-zone-end:gl1yla */}
    </div>
  );
}
