// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { Stepper } from '@/components/ui/stepper'
import { StepperConnector } from '@/components/ui/stepper-connector'
import { Card } from '@/components/ui/card'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:xa24ou */}
      {/* pv-block-start:jipw8f */}
      <DialogWindow size="xl" data-pv-block="jipw8f" data-pv-sketchpad-el="jipw8f"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:ghpyxn */}
          {/* pv-block-start:my9lvs */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="my9lvs">
            {/* pv-editable-zone-start:t7nd3c */}
              {/* pv-block-start:d9f5jx */}
              <div data-pv-block="d9f5jx" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:7l5x7c */}
              {/* pv-block-start:vw310f */}
              <h2 data-pv-block="vw310f" className="text-xl font-semibold text-foreground-default">
                <span></span><span></span><span></span>Import skills to positions from a file
              </h2>
              {/* pv-block-end:vw310f */}
              {/* pv-block-start:rwtf2d */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="rwtf2d" typography="regular">
                <span></span><span></span><span></span>Upload your document and AI will read it and import skills to Tellent HR. <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary hover:opacity-80 transition-opacity">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:rwtf2d */}
              {/* pv-editable-zone-end:7l5x7c */}
              </div>
              {/* pv-block-end:d9f5jx */}
            {/* pv-editable-zone-end:t7nd3c */}
          </div>
          {/* pv-block-end:my9lvs */}
          {/* pv-block-start:cozohu */}
          <div data-pv-block="cozohu" className="flex flex-col p-5 gap-7">
            {/* pv-editable-zone-start:1907kq */}
              {/* pv-block-start:h1e3bn */}
              <Stepper data-pv-block="h1e3bn" fullWidth={false}>
                {/* pv-editable-zone-start:v4z32l */}
                  {/* pv-block-start:jteecl */}
                  <StepCircle labelPosition="right" data-pv-block="jteecl" state="current" number={1} label="Upload file" />
                  {/* pv-block-end:jteecl */}
                  {/* pv-block-start:s7bgd8 */}
                  <StepperConnector data-pv-block="s7bgd8" state="upcoming" />
                  {/* pv-block-end:s7bgd8 */}
                  {/* pv-block-start:kar3j0 */}
                  <StepCircle labelPosition="right" data-pv-block="kar3j0" state="upcoming" number={2} label="Preview skills" />
                  {/* pv-block-end:kar3j0 */}
                  {/* pv-block-start:179spq */}
                  <StepperConnector data-pv-block="179spq" state="upcoming" />
                  {/* pv-block-end:179spq */}
                  {/* pv-block-start:dlc7vi */}
                  <StepCircle labelPosition="right" data-pv-block="dlc7vi" state="upcoming" number={3} label="Apply changes" />
                  {/* pv-block-end:dlc7vi */}
                {/* pv-editable-zone-end:v4z32l */}
              </Stepper>
              {/* pv-block-end:h1e3bn */}

              {/* pv-block-start:v2w9lh */}
              <div data-pv-block="v2w9lh" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:hikm6d */}
                {/* pv-block-start:0fqt9h */}
                <SuperLabel secondaryText="Supported file formats: PDF, DOCX, CSV or XLSX • Max. file size: 5 MB" heading="Upload files with skills" data-pv-block="0fqt9h" primaryText="" />
                {/* pv-block-end:0fqt9h */}
                {/* pv-block-start:bkeq1m */}
                <div className="flex min-h-4 flex-row gap-2 rounded bg-background-primary-subtle p-3" data-pv-block="bkeq1m">
                  {/* pv-editable-zone-start:fzw0z4 */}
                    {/* pv-block-start:mgc6pa */}
                    <div data-pv-block="mgc6pa" className="flex flex-col gap-2">
                      {/* pv-editable-zone-start:a3ohvi */}
                      {/* pv-block-start:72nslo */}
                      <Icon className="text-background-primary-soft" data-pv-block="72nslo" iconSymbol="glyphs:sparkle-bold" size="md" />
                      {/* pv-block-end:72nslo */}
                      {/* pv-editable-zone-end:a3ohvi */}
                    </div>
                    {/* pv-block-end:mgc6pa */}

                    {/* pv-block-start:aa013h */}
                    <div data-pv-block="aa013h" className="flex flex-col gap-2">
                      {/* pv-editable-zone-start:vhplpm */}
                      {/* pv-block-start:4r4rdw */}
                      <TextParagraph data-pv-block="4r4rdw" typography="secondary">
                        <span></span><span></span>No special template is required, Tellent AI is smart enough to analyse any file with company skills. Don’t have such a file yet? <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary hover:opacity-80 transition-opacity">Generate suggested skills in a sheet</a>
                      </TextParagraph>
                      {/* pv-block-end:4r4rdw */}
                      {/* pv-editable-zone-end:vhplpm */}
                    </div>
                    {/* pv-block-end:aa013h */}
                  {/* pv-editable-zone-end:fzw0z4 */}
                </div>
                {/* pv-block-end:bkeq1m */}
                {/* pv-block-start:rnkizt */}
                <Card className="items-center py-8" data-pv-block="rnkizt">
                  {/* pv-editable-zone-start:36ifif */}
                    {/* pv-block-start:vebwo1 */}
                    <Icon className="text-foreground-secondary" data-pv-block="vebwo1" iconSymbol="mdi:cloud-upload-outline" size="2xl" />
                    {/* pv-block-end:vebwo1 */}

                    {/* pv-block-start:edmcen */}
                    <TextParagraph data-pv-block="edmcen" typography="bold-primary">
                      <span></span><span></span><span></span>Upload a file with skills, levels and positions
                    </TextParagraph>
                    {/* pv-block-end:edmcen */}

                    {/* pv-block-start:sgrblg */}
                    <TextParagraph data-pv-block="sgrblg" typography="secondary">
                      <span></span><span></span>Choose and upload a file or drag and drop it here.
                    </TextParagraph>
                    {/* pv-block-end:sgrblg */}
                    {/* pv-block-start:qwiziu */}
                    <Button leftIcon="mdi:upload" data-pv-block="qwiziu" label="Choose file from disk" variant="solid" color="primary" size="md" />
                    {/* pv-block-end:qwiziu */}
                  {/* pv-editable-zone-end:36ifif */}
                </Card>
                {/* pv-block-end:rnkizt */}
                {/* pv-editable-zone-end:hikm6d */}
              </div>
              {/* pv-block-end:v2w9lh */}
            {/* pv-editable-zone-end:1907kq */}
          </div>
          {/* pv-block-end:cozohu */}

          {/* pv-block-start:686fs1 */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 justify-end py-3 px-5" data-pv-block="686fs1">
            {/* pv-editable-zone-start:t7nd3c */}
              {/* pv-block-start:kgo6ug */}
              <div data-pv-block="kgo6ug" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:olib04 */}
                {/* pv-block-start:pxxeyc */}
                <Button data-pv-block="pxxeyc" label="Cancel" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:pxxeyc */}
                {/* pv-editable-zone-end:olib04 */}
              </div>
              {/* pv-block-end:kgo6ug */}
            {/* pv-editable-zone-end:t7nd3c */}
          </div>
          {/* pv-block-end:686fs1 */}
        {/* pv-editable-zone-end:ghpyxn */}
      </DialogWindow>
      {/* pv-block-end:jipw8f */}
      {/* pv-editable-zone-end:xa24ou */}
    </div>
  );
}
