// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { Card } from '@/components/ui/card'
import { Stepper } from '@/components/ui/stepper'
import { StepperConnector } from '@/components/ui/stepper-connector'
import { Container } from '@/components/ui/container'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:nc1nqa */}
      {/* pv-block-start:exm6jg */}
      <DialogWindow size="xl" data-pv-block="exm6jg" data-pv-sketchpad-el="exm6jg"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:gu24cs */}
          {/* pv-block-start:jlpm2v */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="jlpm2v">
            {/* pv-editable-zone-start:t7nd3c */}
              {/* pv-block-start:c39vrv */}
              <div data-pv-block="c39vrv" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:7l5x7c */}
              {/* pv-block-start:xedfkz */}
              <h2 data-pv-block="xedfkz" className="text-xl font-semibold text-foreground-default">
                <span></span><span></span><span></span>Import skills to positions from a file
              </h2>
              {/* pv-block-end:xedfkz */}
              {/* pv-block-start:ahfwpg */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="ahfwpg" typography="regular">
                <span></span><span></span><span></span>Upload your document and AI will read it and import skills to Tellent HR. <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary hover:opacity-80 transition-opacity">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:ahfwpg */}
              {/* pv-editable-zone-end:7l5x7c */}
              </div>
              {/* pv-block-end:c39vrv */}
            {/* pv-editable-zone-end:t7nd3c */}
          </div>
          {/* pv-block-end:jlpm2v */}
          {/* pv-block-start:e5voje */}
          <div data-pv-block="e5voje" className="flex flex-col p-5 gap-7">
            {/* pv-editable-zone-start:hb3knb */}
              {/* pv-block-start:8vnpes */}
              <Stepper data-pv-block="8vnpes" fullWidth={false}>
                {/* pv-editable-zone-start:v4z32l */}
                  {/* pv-block-start:m13np6 */}
                  <StepCircle labelPosition="right" data-pv-block="m13np6" state="done" number={1} label="Upload file" />
                  {/* pv-block-end:m13np6 */}
                  {/* pv-block-start:v16pbl */}
                  <StepperConnector data-pv-block="v16pbl" state="upcoming" />
                  {/* pv-block-end:v16pbl */}
                  {/* pv-block-start:27weus */}
                  <StepCircle labelPosition="right" data-pv-block="27weus" state="current" number={2} label="Preview skills" />
                  {/* pv-block-end:27weus */}
                  {/* pv-block-start:0ujm7q */}
                  <StepperConnector data-pv-block="0ujm7q" state="upcoming" />
                  {/* pv-block-end:0ujm7q */}
                  {/* pv-block-start:wgqg5q */}
                  <StepCircle labelPosition="right" data-pv-block="wgqg5q" state="upcoming" number={3} label="Apply changes" />
                  {/* pv-block-end:wgqg5q */}
                {/* pv-editable-zone-end:v4z32l */}
              </Stepper>
              {/* pv-block-end:8vnpes */}
              {/* pv-block-start:m7kral */}
              <div data-tooltip-text="This section only appears if Custom number of proficiency levels is selected" data-pv-block="m7kral" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:dy3ds8 */}
                {/* pv-block-start:lvjh8x */}
                <SuperLabel secondaryText="AI can make mistakes. Before applying changes, check if it correctly read your file." heading="Preview skills to import" data-pv-block="lvjh8x" primaryText="" />
                {/* pv-block-end:lvjh8x */}

                {/* pv-block-start:e6ic84 */}
                <SuperLabel secondaryText="" heading="(We will do this later)" data-pv-block="e6ic84" primaryText="" />
                {/* pv-block-end:e6ic84 */}
                {/* pv-editable-zone-end:dy3ds8 */}
              </div>
              {/* pv-block-end:m7kral */}
              {/* pv-block-start:vs3109 */}
              <Container data-pv-block="vs3109">
                {/* pv-editable-zone-start:gvn75e */}
                {/* pv-editable-zone-end:gvn75e */}
              </Container>
              {/* pv-block-end:vs3109 */}
            {/* pv-editable-zone-end:hb3knb */}
          </div>
          {/* pv-block-end:e5voje */}

          {/* pv-block-start:mbv43u */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 py-3 px-5 justify-between" data-pv-block="mbv43u">
            {/* pv-editable-zone-start:2mi6w3 */}
              {/* pv-block-start:x4y4gr */}
              <Button leftIcon="mdi:arrow-back" data-pv-block="x4y4gr" label="Back" variant="ghost" color="neutral" size="md"  />
              {/* pv-block-end:x4y4gr */}
              {/* pv-block-start:gh1jlr */}
              <div data-pv-block="gh1jlr" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:2x30wg */}
                {/* pv-block-start:t8stw0 */}
                <Button leftIcon="mdi:check"  data-pv-block="t8stw0" label="Apply changes" variant="solid" color="primary" size="md"  />
                {/* pv-block-end:t8stw0 */}
                {/* pv-editable-zone-end:2x30wg */}
              </div>
              {/* pv-block-end:gh1jlr */}
            {/* pv-editable-zone-end:2mi6w3 */}
          </div>
          {/* pv-block-end:mbv43u */}
        {/* pv-editable-zone-end:gu24cs */}
      </DialogWindow>
      {/* pv-block-end:exm6jg */}
      {/* pv-editable-zone-end:nc1nqa */}
    </div>
  );
}
