// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:rtzayt */}
      {/* pv-block-start:1obgh8 */}
      <DialogWindow size="xl" data-pv-block="1obgh8" data-pv-sketchpad-el="1obgh8"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:jcx4p4 */}
          {/* pv-block-start:k4mn1h */}
          <div data-pv-block="k4mn1h" className="flex flex-col gap-2 p-12">
            {/* pv-editable-zone-start:xcg13x */}
              {/* pv-block-start:2gcnka */}
              <div data-pv-block="2gcnka" className="flex flex-row items-start gap-16">
                {/* pv-editable-zone-start:wo74jp */}
                {/* pv-block-start:6mrebx */}
                <div data-pv-block="6mrebx" className="flex flex-col gap-8">
                {/* pv-editable-zone-start:enyhfe */}
                {/* pv-block-start:ppsjsl */}
                <div data-pv-block="ppsjsl" className="flex flex-col gap-4">
                {/* pv-editable-zone-start:8be0rh */}
                {/* pv-block-start:rf94ku */}
                <h2 data-pv-block="rf94ku" className="font-semibold text-foreground-default text-2xl">
                <span></span><span></span>Generate suggested skills in a spreadsheet
                </h2>
                {/* pv-block-end:rf94ku */}
                {/* pv-block-start:fbnso8 */}
                <TextParagraph className="pt-0.5" data-pv-block="fbnso8" typography="regular">
                  <span></span>Don’t have a document that defines skills in your company yet? No worries, we can help you kick-off this project!
                </TextParagraph>
                {/* pv-block-end:fbnso8 */}
                {/* pv-editable-zone-end:8be0rh */}
                </div>
                {/* pv-block-end:ppsjsl */}
                {/* pv-block-start:88rls2 */}
                <div data-pv-block="88rls2" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:4v2vz4 */}
                {/* pv-block-start:gwhw15 */}
                <div className="flex flex-col items-start relative pb-6 min-h-16" data-pv-block="gwhw15">
                {/* pv-editable-zone-start:inside-gwhw15 */}
                {/* pv-block-start:j88xbh */}
                <div data-pv-block="j88xbh" className="flex flex-row items-start justify-start gap-3">
                {/* pv-editable-zone-start:qyqjnc */}
                {/* pv-block-start:ucan3m */}
                <StepCircle data-pv-block="ucan3m" state="current" number={1} />
                {/* pv-block-end:ucan3m */}
                {/* pv-block-start:1zpetx */}
                <TextParagraph className="pt-0.5" data-pv-block="1zpetx" typography="regular">
                  <span></span><span></span>Generate a file with all your positions and suggested skills
                </TextParagraph>
                {/* pv-block-end:1zpetx */}
                {/* pv-editable-zone-end:qyqjnc */}
                </div>
                {/* pv-block-end:j88xbh */}
                
                  {/* pv-block-start:v7f6k0 */}
                  <div className="flex flex-col w-6 items-center absolute top-8 bottom-0 min-h-2" data-pv-block="v7f6k0">
                    {/* pv-editable-zone-start:inside-v7f6k0 */}
                      {/* pv-block-start:xpbdiz */}
                      <div className="flex flex-col min-h-4 w-px bg-background-primary flex-1" data-pv-block="xpbdiz">
                        {/* pv-editable-zone-start:inside-xpbdiz */}
                        {/* pv-editable-zone-end:inside-xpbdiz */}
                      </div>
                      {/* pv-block-end:xpbdiz */}
                    {/* pv-editable-zone-end:inside-v7f6k0 */}
                  </div>
                  {/* pv-block-end:v7f6k0 */}
                {/* pv-editable-zone-end:inside-gwhw15 */}
                </div>
                {/* pv-block-end:gwhw15 */}

                {/* pv-block-start:hx1izr */}
                <div className="flex flex-col items-start relative pb-6 min-h-16" data-pv-block="hx1izr">
                {/* pv-editable-zone-start:inside-hx1izr */}
                {/* pv-block-start:ak7cus */}
                <div data-pv-block="ak7cus" className="flex flex-row items-start justify-start gap-3">
                {/* pv-editable-zone-start:qyqjnc */}
                {/* pv-block-start:s9muwj */}
                <StepCircle data-pv-block="s9muwj" state="current" number={1} />
                {/* pv-block-end:s9muwj */}
                {/* pv-block-start:r9c9b0 */}
                <TextParagraph className="pt-0.5" data-pv-block="r9c9b0" typography="regular">
                  <span></span>Collaborate on the file in your favourite tools, like Google Sheets
                </TextParagraph>
                {/* pv-block-end:r9c9b0 */}
                {/* pv-editable-zone-end:qyqjnc */}
                </div>
                {/* pv-block-end:ak7cus */}
                
                  {/* pv-block-start:kgphdx */}
                  <div className="flex flex-col w-6 items-center absolute top-8 bottom-0 min-h-2" data-pv-block="kgphdx">
                    {/* pv-editable-zone-start:inside-kgphdx */}
                      {/* pv-block-start:hdc03o */}
                      <div className="flex flex-col min-h-4 w-px bg-background-primary flex-1" data-pv-block="hdc03o">
                        {/* pv-editable-zone-start:inside-hdc03o */}
                        {/* pv-editable-zone-end:inside-hdc03o */}
                      </div>
                      {/* pv-block-end:hdc03o */}
                    {/* pv-editable-zone-end:inside-kgphdx */}
                  </div>
                  {/* pv-block-end:kgphdx */}
                {/* pv-editable-zone-end:inside-hx1izr */}
                </div>
                {/* pv-block-end:hx1izr */}

                {/* pv-block-start:tiw2gl */}
                <div className="flex flex-col items-start relative pb-6 min-h-0" data-pv-block="tiw2gl">
                {/* pv-editable-zone-start:inside-tiw2gl */}
                {/* pv-block-start:lwlyb3 */}
                <div data-pv-block="lwlyb3" className="flex flex-row items-start justify-start gap-3">
                {/* pv-editable-zone-start:qyqjnc */}
                {/* pv-block-start:7s71o1 */}
                <StepCircle data-pv-block="7s71o1" state="current" number={1} />
                {/* pv-block-end:7s71o1 */}
                {/* pv-block-start:iejkht */}
                <TextParagraph className="pt-0.5" data-pv-block="iejkht" typography="regular">
                  <span></span>Once you’re done, import the file to Tellent HR
                </TextParagraph>
                {/* pv-block-end:iejkht */}
                {/* pv-editable-zone-end:qyqjnc */}
                </div>
                {/* pv-block-end:lwlyb3 */}
                
                  {/* pv-block-start:mquzyu */}
                  <div className="flex-col w-6 items-center absolute top-8 bottom-0 min-h-2 hidden" data-pv-block="mquzyu">
                    {/* pv-editable-zone-start:inside-mquzyu */}
                      {/* pv-block-start:anxb9y */}
                      <div className="flex flex-col min-h-4 w-px bg-background-primary flex-1" data-pv-block="anxb9y">
                        {/* pv-editable-zone-start:inside-anxb9y */}
                        {/* pv-editable-zone-end:inside-anxb9y */}
                      </div>
                      {/* pv-block-end:anxb9y */}
                    {/* pv-editable-zone-end:inside-mquzyu */}
                  </div>
                  {/* pv-block-end:mquzyu */}
                {/* pv-editable-zone-end:inside-tiw2gl */}
                </div>
                {/* pv-block-end:tiw2gl */}
                {/* pv-editable-zone-end:4v2vz4 */}
                </div>
                {/* pv-block-end:88rls2 */}
                {/* pv-editable-zone-end:enyhfe */}
                </div>
                {/* pv-block-end:6mrebx */}
                {/* pv-block-start:mk6tvu */}
                <Image data-pv-block="mk6tvu" className="bg-cover bg-center bg-no-repeat w-full bg-[url('/src/images/from-protovibe/ai-spreadsheet-illustration.svg')] aspect-[133/174] max-w-[258px]" />
                {/* pv-block-end:mk6tvu */}
                {/* pv-editable-zone-end:wo74jp */}
              </div>
              {/* pv-block-end:2gcnka */}
            {/* pv-editable-zone-end:xcg13x */}
          </div>
          {/* pv-block-end:k4mn1h */}
          {/* pv-block-start:u9rjmz */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 justify-between py-3 px-5" data-pv-block="u9rjmz">
            {/* pv-editable-zone-start:inside-u9rjmz */}
              {/* pv-block-start:iozn25 */}
              <Checkbox data-pv-block="iozn25" primaryText="Don't show this intro again" />
              {/* pv-block-end:iozn25 */}
              {/* pv-block-start:zlkw0l */}
              <div data-pv-block="zlkw0l" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:dwfhaa */}
                {/* pv-block-start:k89jww */}
                <Button data-pv-block="k89jww" label="Cancel" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:k89jww */}
                {/* pv-block-start:kr4iot */}
                <Button rightIcon="mdi:arrow-right" data-pv-block="kr4iot" label="Let's start" variant="solid" color="primary" size="md"  />
                {/* pv-block-end:kr4iot */}
                {/* pv-editable-zone-end:dwfhaa */}
              </div>
              {/* pv-block-end:zlkw0l */}
            {/* pv-editable-zone-end:inside-u9rjmz */}
          </div>
          {/* pv-block-end:u9rjmz */}
        {/* pv-editable-zone-end:jcx4p4 */}
      </DialogWindow>
      {/* pv-block-end:1obgh8 */}
      {/* pv-editable-zone-end:rtzayt */}
    </div>
  );
}
