// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { PreloaderSpinner } from '@/components/ui/preloader-spinner'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:ltj58r */}
      {/* pv-block-start:t4c5ob */}
      <DialogWindow size="xl" data-pv-block="t4c5ob" data-pv-sketchpad-el="t4c5ob"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:a760ay */}
          {/* pv-block-start:qcnj1k */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="qcnj1k">
            {/* pv-editable-zone-start:rmnciv */}
              {/* pv-block-start:wflmtv */}
              <div data-pv-block="wflmtv" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:ux6dfh */}
              {/* pv-block-start:bw2j4o */}
              <h2 data-pv-block="bw2j4o" className="text-xl font-semibold text-foreground-default">
                <span></span><span></span><span></span>Import skills to positions from a file
              </h2>
              {/* pv-block-end:bw2j4o */}
              {/* pv-block-start:t23xtp */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="t23xtp" typography="regular">
                <span></span><span></span><span></span>Upload your document and AI will read it and import skills to Tellent HR. <a className="text-foreground-primary hover:opacity-80 transition-opacity" href="https://" target="_blank" rel="noopener noreferrer">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:t23xtp */}
              {/* pv-editable-zone-end:ux6dfh */}
              </div>
              {/* pv-block-end:wflmtv */}
            {/* pv-editable-zone-end:rmnciv */}
          </div>
          {/* pv-block-end:qcnj1k */}
          {/* pv-block-start:1m09ay */}
          <div data-pv-block="1m09ay" className="flex flex-col gap-4 items-center p-5">
            {/* pv-editable-zone-start:3gvhjd */}
              {/* pv-block-start:uoivqm */}
              <div data-pv-block="uoivqm" className="flex flex-col gap-2 pt-4">
                {/* pv-editable-zone-start:n7yumz */}
                {/* pv-block-start:v647n2 */}
                <PreloaderSpinner data-pv-block="v647n2" size="xl" />
                {/* pv-block-end:v647n2 */}
                {/* pv-block-start:k6zv6d */}
                <div data-pv-block="k6zv6d" className="flex flex-col gap-0">
                  {/* pv-editable-zone-start:clgc05 */}
                  {/* pv-block-start:nzx2lw */}
                  <TextParagraph className="text-center" data-pv-block="nzx2lw" typography="bold-primary">
                    <span></span><span></span><span></span>Analysing your skills...
                  </TextParagraph>
                  {/* pv-block-end:nzx2lw */}
                  {/* pv-block-start:w63ldn */}
                  <TextParagraph className="text-center" data-pv-block="w63ldn" typography="regular">
                    <span></span><span></span><span></span>It will take about 30 seconds. In the meantime your can play the game below.
                  </TextParagraph>
                  {/* pv-block-end:w63ldn */}
                  {/* pv-editable-zone-end:clgc05 */}
                </div>
                {/* pv-block-end:k6zv6d */}
                {/* pv-editable-zone-end:n7yumz */}
              </div>
              {/* pv-block-end:uoivqm */}



              {/* pv-block-start:3zvcri */}
              <div className="flex flex-col min-h-32 w-full px-8 h-72" data-pv-block="3zvcri">
                {/* pv-editable-zone-start:3dgjq3 */}
                {/* pv-block-start:sk482h */}
                <iframe
                  data-pv-block="sk482h"
                  src="https://thriving-bombolone-1cfc2b.netlify.app/"
                  className="w-full h-full"
                  frameBorder="0"
                />
                {/* pv-block-end:sk482h */}
                {/* pv-editable-zone-end:3dgjq3 */}
              </div>
              {/* pv-block-end:3zvcri */}
            {/* pv-editable-zone-end:3gvhjd */}
          </div>
          {/* pv-block-end:1m09ay */}

          {/* pv-block-start:1pk9cx */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 py-3 px-5 justify-start" data-pv-block="1pk9cx">
            {/* pv-editable-zone-start:rmnciv */}
              {/* pv-block-start:3ez3j3 */}
              <div data-pv-block="3ez3j3" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:oaa0c1 */}
                {/* pv-block-start:5hq39d */}
                <Button leftIcon="mdi:arrow-left" data-pv-block="5hq39d" label="Back" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:5hq39d */}
                {/* pv-editable-zone-end:oaa0c1 */}
              </div>
              {/* pv-block-end:3ez3j3 */}
            {/* pv-editable-zone-end:rmnciv */}
          </div>
          {/* pv-block-end:1pk9cx */}
        {/* pv-editable-zone-end:a760ay */}
      </DialogWindow>
      {/* pv-block-end:t4c5ob */}
      {/* pv-editable-zone-end:ltj58r */}
    </div>
  );
}
